#!/usr/bin/env python3
"""
Plot CMB power spectrum from CLASS .dat files
This script reads the output files generated by the C executable and plots them.
"""

import numpy as np
import matplotlib.pyplot as plt

def read_class_cl_file(filename):
    """
    Read CLASS Cl output file and return l and Cl data
    
    Parameters:
    filename: path to CLASS _cl.dat file
    
    Returns:
    l: multipole values
    cl_tt: temperature power spectrum C_l values
    """
    # Read the file, skipping header lines starting with #
    data = np.loadtxt(filename, comments='#')
    
    l = data[:, 0].astype(int)  # First column: multipole l
    cl_tt = data[:, 1]          # Second column: TT power spectrum
    
    return l, cl_tt

def plot_cmb_power_spectrum(filename, nu_spacing, label=None, color=None):
    """
    Plot CMB power spectrum from CLASS output file
    
    Parameters:
    filename: path to CLASS _cl.dat file
    nu_spacing: nu_spacing value used (for labeling)
    label: custom label for the plot
    color: color for the plot line
    """
    try:
        l, cl_tt = read_class_cl_file(filename)
        
        # Convert to D_l = l(l+1)C_l/(2π) * (T_CMB)^2 in μK^2
        # CLASS outputs C_l in dimensionless units, we need to convert
        T_CMB = 2.7255  # CMB temperature in K
        conversion_factor = (1e6 * T_CMB)**2  # Convert to μK^2
        
        # CLASS already outputs l(l+1)C_l/(2π), so we just need unit conversion
        D_l = cl_tt * conversion_factor
        
        if label is None:
            label = f"nu_spacing = {nu_spacing}"
        
        plt.loglog(l, D_l, label=label, color=color, linewidth=1.5)
        
        print(f"Successfully plotted {filename}")
        print(f"l range: {l.min()} to {l.max()}")
        print(f"D_l range: {D_l.min():.2e} to {D_l.max():.2e} μK²")
        
        return l, D_l
        
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        return None, None

# Main plotting
if __name__ == "__main__":
    
    plt.figure(figsize=(10, 6))
    
    # Plot the latest output file
    filename = "test_closed_05_cl.dat"
    nu_spacing = 3  # Based on your test_closed_universe.ini
    
    l, D_l = plot_cmb_power_spectrum(filename, nu_spacing, color='C0')
    
    if l is not None:
        # Set plot properties
        plt.xlabel(r'$\ell$', fontsize=14)
        plt.ylabel(r'$\mathcal{D}_\ell^{TT} = \ell(\ell+1)C_\ell/(2\pi) \quad [\mu\mathrm{K}^2]$', fontsize=14)
        plt.title('CMB Temperature Power Spectrum (Closed Universe)', fontsize=16)
        plt.grid(True, alpha=0.3)
        plt.legend(fontsize=12)
        plt.xlim(2, 1000)
        
        # Save the plot
        plt.tight_layout()
        plt.savefig(f'CMB_nu_spacing_{nu_spacing}_from_dat.pdf', dpi=300, bbox_inches='tight')
        plt.savefig(f'CMB_nu_spacing_{nu_spacing}_from_dat.png', dpi=300, bbox_inches='tight')
        plt.show()
        
        print(f"\nPlot saved as CMB_nu_spacing_{nu_spacing}_from_dat.pdf")
    else:
        print("Failed to plot - no valid data found")

    # Optionally compare multiple files if they exist
    print("\nAvailable CLASS output files:")
    import glob
    cl_files = glob.glob("test_closed_*_cl.dat")
    for file in sorted(cl_files):
        print(f"  {file}")